### ISSUE TITLE
Euromap Instances Test: Optional Placeholders - UaModeler bug

### ISSUE THREAD

**Issue by MartinaFelberFEM** [matkonnerth/nodesetLoader#118]
To test euromap variable instances we provide a euromapinstances XML. 
But selection of Optional Placeholder does not work with UaModeler

![image](https://user-images.githubusercontent.com/50486106/84026107-ff2ee380-a98c-11ea-95b8-ba439e217a15.png)

**Comment by matkonnerth** [comment]
I will close this here, cannot provide a fix.
