### ISSUE TITLE
Too simple type names: TNode, TNodeId

### ISSUE THREAD

**Issue by gveector** [matkonnerth/nodesetLoader#160]
In NodesetLoader.h "TNode" / TNodeId.h "TNodeId" - is too simple type names, causes a type name conflict when using the nodesetLoader in projects (Pascal/Delphi - naming style).

Please change this internal names by adding a prefix or suffix to them. 
For example (NL - NodesetLoader):
TNode -> TNLNode / TNodeNL
TNodeId -> TNLNodeId / TNodeIdNL

Sorry to bother you.

**Comment by matkonnerth** [comment]
I understand that, namespaces are missing in C ;)

I would vote for a _NL_ prefix for types, for example:
_NL_Node_
_NL_NodeId_

Most of the existing public functions are already prefixed with _NodesetLoader_, I will not change that.

**Comment by matkonnerth** [comment]
@gveector : please take a look a this PR https://github.com/matkonnerth/nodesetLoader/pull/161

**Comment by matkonnerth** [comment]
should be fixed with https://github.com/matkonnerth/nodesetLoader/pull/161

**Comment by gveector** [comment]
Excellent!
