### ISSUE TITLE
Error while making

### ISSUE THREAD

**Issue by Hfiazihilscher** [matkonnerth/nodesetLoader#163]
Hello i am new in this topic and need some help. I work with the options:
ENABALE_CONAN ON
ENABLE_BACKEND_OPEN62541 ON

while making i recseive this error:

nodesetLoader/backends/open62541/src/DataTypeImporter.c:369:30: error: incompatible types when assigning to type ‘UA_UInt32’ {aka ‘unsigned int’} from type ‘UA_NodeId’ {aka ‘struct <anonymous>’}
  369 |     type->binaryEncodingId = getBinaryEncodingId(node);
         |                                              ^~~~~~~~~~~~~~~~~~~
nodesetLoader/backends/open62541/src/DataTypeImporter.c: In function ‘EnumDataType_init’:
/nodesetLoader/backends/open62541/src/DataTypeImporter.c:383:34:
 error: incompatible types when assigning to type ‘UA_UInt32’ {aka ‘unsigned int’} from type ‘UA_NodeId’ {aka ‘const struct <anonymous>’}
  383 |     enumType->binaryEncodingId = UA_NODEID_NULL;
         |                                                        ^~~~~~~~~~~~~~

Could the problem be: while making the compiler dont find the right Header-files? 

![Error making](https://user-images.githubusercontent.com/89186289/130031169-26b2b3ea-d69d-49d3-a260-016408e5b37c.PNG)

**Comment by matkonnerth** [comment]
please disable conan usage and use the 1.2 branch of the open62541. The binary encoding id was changed from a integer to a NodeId.

**Comment by matkonnerth** [comment]
I removed the open62541 library as conan dependency, because nodesetLoader needs version >= 1.2 of open26541, and this version is currently not available via conan: https://github.com/matkonnerth/nodesetLoader/pull/164

Hopefully you can upgrade to open62541 version >= 1.2 in your project, otherwise we have to figure out another solution.

**Comment by Hfiazihilscher** [comment]
i already used this library Version 1.2. i will try it and bind the library with another way. Thanks a lot!

**Comment by Hfiazihilscher** [comment]
![still searching](https://user-images.githubusercontent.com/89186289/130410240-c4d7daca-2e29-422e-9f3f-8ecd69c8e470.PNG)

**Comment by matkonnerth** [comment]
it seems that you are using a master branch version of the open62541, here the UA_DataTypeMember from master:

https://github.com/open62541/open62541/blob/530e3c0aaffd07d85f260e1713de39bf2fd22181/include/open62541/types.h#L950

and here the one from v1.2.2
https://github.com/open62541/open62541/blob/ecf5a703785877a8719a0cda863a98455f7d5d12/include/open62541/types.h#L945

currently the nodesetLoader supports only the 1.2.2 version, but I am working on making it also work with the master branch:
https://github.com/matkonnerth/nodesetLoader/pull/165

**Comment by Hfiazihilscher** [comment]
Thanks for your detailed help. After I installed the branch, I had the problem again which I posted last. I had to switch off the option: USE_MEMBERTYPE_INDEX. After that it compiled and I can now load my own nodesets!
