### ISSUE TITLE
validate xml nodeset?

### ISSUE THREAD

**Issue by matkonnerth** [matkonnerth/nodesetLoader#23]
Can the sax parser of libxml also validate the nodeset xml?

**Comment by MartinaFelberFEM** [comment]
It seems that libxml2 supports schema validation, but it's work in progress? 
http://xmlsoft.org/html/libxml-xmlschemas.html
It seems that XSD version 1.1 is not supported ...

**Comment by matkonnerth** [comment]
I will close this point, users of the library should validate upfront.
