### ISSUE TITLE
Description attribute is missing

### ISSUE THREAD

**Issue by MartinaFelberFEM** [matkonnerth/nodesetLoader#56]
Sometimes description attribute is missing.
Tested with DI nodeset.
E.g. node: BaseObjectType - TopologyElementType - GroupIdentifier

reference server:
![image](https://user-images.githubusercontent.com/50486106/81178539-a42e5900-8fa8-11ea-8b76-9093afe30c3e.png)

test server:
![image](https://user-images.githubusercontent.com/50486106/81178619-c32ceb00-8fa8-11ea-8f14-242c129c9456.png)

**Comment by matkonnerth** [comment]
I can confirm this, description tag is not considered at the moment.

**Comment by matkonnerth** [comment]
fixed by https://github.com/matkonnerth/nodesetLoader/pull/58

**Comment by MartinaFelberFEM** [comment]
Great! I have just tested it!
