### ISSUE TITLE
PLCopen nodeset import does not work

### ISSUE THREAD

**Issue by MartinaFelberFEM** [matkonnerth/nodesetLoader#57]
It seems that PLCopen nodeset import does not work anymore ? 
I have tested with current master. f238d09a6f2cde1baeb5e397395e9339d27c9860

Function NodesetLoader_loadFile() returns true
There are no error messages or warnings.

Nodeset DI and testNodeSet.xml could be loaded.
But PLCopen namespace is missing

![image](https://user-images.githubusercontent.com/50486106/81179592-29fed400-8faa-11ea-9573-b04d224d71c5.png)

Can you confirm?

**Comment by matkonnerth** [comment]
ok, that looks interesting. I've tested it with _backends/open62541/examples/server /usr/local/share/open62541/tools/ua-nodeset/DI/Opc.Ua.Di.NodeSet2.xml /usr/local/share/open62541/tools/ua-nodeset/PLCopen/Opc.Ua.Plc.NodeSet2.xml_

here's the result:
![image](https://user-images.githubusercontent.com/2398220/81189732-35a4c780-8fb7-11ea-94ff-09a18d6d5cad.png)

**Comment by MartinaFelberFEM** [comment]
I am very sorry, I have used the wrong nodeset (OpcUaPLCopenModel.xml) 
:(
Sorry for the inconvenience.
