### ISSUE TITLE
ReferenceTypes: Attributes InverseName and Symmetric

### ISSUE THREAD

**Issue by MartinaFelberFEM** [matkonnerth/nodesetLoader#59]
Hi!

I think the referencetype attributes InverseName and Symmetric are not properly set.

reference server:
![image](https://user-images.githubusercontent.com/50486106/81343988-3f612480-90b6-11ea-9cf5-fadae0c45254.png)
Symmetric = false

test server:
![image](https://user-images.githubusercontent.com/50486106/81343746-d7124300-90b5-11ea-9e83-f09c648a76da.png)
Symmetric = true

Other examples:
DI nodeset:
Id = ns=2;i=6031 REFERENCETYPE
BrowseName = ns=2;IsOnline

PLCopen:
Id = ns=3;i=4001 REFERENCETYPE
Id = ns=3;i=4002 REFERENCETYPE
Id = ns=3;i=4003 REFERENCETYPE
Id = ns=3;i=4004 REFERENCETYPE
...

**Comment by matkonnerth** [comment]
Yes, you are right. Here the fix: https://github.com/matkonnerth/nodesetLoader/pull/60

**Comment by MartinaFelberFEM** [comment]
Great! I have just tested it with current master branch. :)

Now I only have one difference left for nodeSets DI and PLCopen!
