### ISSUE TITLE
Euromap test: EventNotifier attribute

### ISSUE THREAD

**Issue by MartinaFelberFEM** [matkonnerth/nodesetLoader#78]
I think the nodesetLoader does not set the EventNotifier attribute correctly.
At least it does not match with the reference server.
Tested with branch euormap_test

E.g. Object ProductionDatasetLists: BaseObjectType/ProductionDataSetManagementType/ProductionDataSetLists

reference server: EventNotifier = SubscribeToEvents
![image](https://user-images.githubusercontent.com/50486106/81601533-4a27fc00-93cb-11ea-872d-7ea679aca415.png)

test server: EventNotifier = None
![image](https://user-images.githubusercontent.com/50486106/81601652-852a2f80-93cb-11ea-8766-e3a9a534056a.png)

xml Definition: Opc.Ua.PlasticsRubber.GeneralTypes.NodeSet2.xml
```xml
    <UAObject ParentNodeId="ns=1;i=1008" EventNotifier="1" NodeId="ns=1;i=5007" BrowseName="1:ProductionDatasetLists">
        <DisplayName>ProductionDatasetLists</DisplayName>
        <Description>Functions for exchanging information on the available production datasets on client and server</Description>
        <References>
            <Reference ReferenceType="HasComponent">ns=1;i=7005</Reference>
            <Reference ReferenceType="HasModellingRule">i=80</Reference>
            <Reference ReferenceType="HasComponent" IsForward="false">ns=1;i=1008</Reference>
            <Reference ReferenceType="HasTypeDefinition">ns=1;i=1003</Reference>
            <Reference ReferenceType="GeneratesEvent">ns=1;i=1040</Reference>
            <Reference ReferenceType="HasComponent">ns=1;i=7006</Reference>
        </References>
    </UAObject>
```

The XML definition does not specify the EventNotifier attribute ...
How can you know if you have to set the EventNotifier attribute?
Maybe you have to set it, if the node is of class Object and it has a GeneratesEvent reference?

How can you know if you have to set the EventNotifier attribute for historizing events? (HistoryRead/HistoryWrite)

**Comment by matkonnerth** [comment]
I can confirm, EventNotifier attribute is currently not parsed, simply have to add it, wanna try? ;)

Don't understand your questions, in the your xml snippet, there is the attribute:
EventNotifier="1"

**Comment by MartinaFelberFEM** [comment]
Ah sorry, I have totally overlooked the EventNotifier attribute in the XML

Yes, I would like to try :)
I will create a PR for EventNotifiers

**Comment by matkonnerth** [comment]
fixed by https://github.com/matkonnerth/nodesetLoader/pull/89
